name: Deploy doc

on:
  workflow_run:
    workflows: ["Build doc"]
    types:
      - completed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
    steps:
      # Manage workflow deployment status
      - name: 'Commit Status: Set Workflow Status as Pending'
        uses: myrotvorets/set-commit-status-action@1.1.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          # Should match `env.PR_HEADSHA` when triggered by `pull_request` event workflow,
          # Avoids failure of ENV being unavailable if job fails early:
          sha: ${{ github.event.workflow_run.head_sha }}
          context: 'Deploy Preview (pull_request => workflow_run)'

      # - name: Get pull request number
      #   uses: actions/github-script@v6
      #   id: pull-request-number
      #   with:
      #     result-encoding: string
      #     script: |
      #       const unzipper = require('unzipper');
      #       const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         run_id: ${{github.event.workflow_run.id}}
      #       });
      #       const artifact = artifacts.data.artifacts.filter(
      #         artifact => artifact.name === 'pr'
      #       )[0];
      #       if (!artifact) {
      #         throw new Error('No pr artifact found');
      #       }
      #       const download = await github.rest.actions.downloadArtifact({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         artifact_id: artifact.id,
      #         archive_format: 'zip'
      #       });
      #       const directory = await unzipper.Open.buffer(Buffer.from(download.data));
      #       const file = directory.files.find(d => d.path === 'number');
      #       const content = await file.buffer();
      #       return content.toString();
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: doc-build.yml
          pr: ${{steps.pull-request-number.outputs.result}}
          name: doc

      - name: Get pull request number
        id: pull-request-number
        run: |
          export PR_NUMBER=$(cat pr_number)
          echo "{result}={${PR_NUMBER}}" >> $GITHUB_OUTPUT

      - run: ls -ltrh
      - run: ls -ltrh _build/html
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install --global netlify-cli@6
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
        run: netlify deploy --dir=_build/html --alias=doc-preview-${{steps.pull-request-number.outputs.result}}

      - name: 'Commit Status: Update deployment status'
        uses: myrotvorets/set-commit-status-action@1.1.6
        # Always run this step regardless of job failing early
        if: always()
        env:
          DEPLOY_SUCCESS: Successfully deployed preview.
          DEPLOY_FAILURE: Failed to deploy preview.
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status == 'success' && 'success' || 'failure' }}
          sha: ${{ github.event.workflow_run.head_sha }}
          context: 'Deploy Preview (pull_request => workflow_run)'
          description: ${{ job.status == 'success' && env.DEPLOY_SUCCESS || env.DEPLOY_FAILURE }}
          targetUrl: https://doc-preview-${{steps.pull-request-number.outputs.result}}--lesteve-test-netlify.netlify.app
